---
  # setup directories
  - name: create directory for certificates
    file:
      path: "{{ kubernetes_install_dir }}"
      state: directory

  # copy CA certificate
  - name: copy {{ kubernetes_certificates_ca_file_name }}
    copy:
      src: "{{ tls_directory }}/ca.pem"
      dest: "{{ kubernetes_certificates.ca }}"
      owner: "{{ kubernetes_certificates_owner }}"
      group: "{{ kubernetes_certificates_group }}"
      mode: "{{ kubernetes_certificates_mode }}"
    
  # copy kubernetes control plane certificates
  - name: copy master node TLS assets
    copy:
      src: "{{ tls_directory }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ kubernetes_certificates_owner }}"
      group: "{{ kubernetes_certificates_group }}"
      mode: "{{ kubernetes_certificates_mode }}"
    when: "'master' in group_names"
    with_items:
      - src: "etcd-client.pem"
        dest: "{{ kubernetes_certificates.etcd_client }}"
      - src: "etcd-client-key.pem"
        dest: "{{ kubernetes_certificates.etcd_client_key }}"
      - src: "{{ inventory_hostname }}-apiserver.pem"
        dest: "{{ kubernetes_certificates.api_server }}"
      - src: "{{inventory_hostname}}-apiserver-key.pem"
        dest: "{{ kubernetes_certificates.api_server_key }}"
      - src: "kube-scheduler.pem"
        dest: "{{ kubernetes_certificates.scheduler }}"
      - src: "kube-scheduler-key.pem"
        dest: "{{ kubernetes_certificates.scheduler_key }}"
      - src: "kube-controller-manager.pem"
        dest: "{{ kubernetes_certificates.controller_manager }}"
      - src: "kube-controller-manager-key.pem"
        dest: "{{ kubernetes_certificates.controller_manager_key }}"
      - src: "service-account.pem"
        dest: "{{ kubernetes_certificates.service_account }}"
      - src: "service-account-key.pem"
        dest: "{{ kubernetes_certificates.service_account_key }}"

  # copy kubelet and kube-proxy certificates
  - name: deploy kubernetes node client certificates
    copy:
      src: "{{ tls_directory }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ kubernetes_certificates_owner }}"
      group: "{{ kubernetes_certificates_group }}"
      mode: "{{ kubernetes_certificates_mode }}"
    when: "['master','worker','ingress','storage'] | intersect(group_names) | length > 0"
    with_items:
      - src: "{{ inventory_hostname }}-kubelet.pem"
        dest: "{{ kubernetes_certificates.kubelet }}"
      - src: "{{ inventory_hostname }}-kubelet-key.pem"
        dest: "{{ kubernetes_certificates.kubelet_key }}"
      - src: "kube-proxy.pem"
        dest: "{{ kubernetes_certificates.kube_proxy }}"
      - src: "kube-proxy-key.pem"
        dest: "{{ kubernetes_certificates.kube_proxy_key }}"
      - src: "etcd-client.pem"
        dest: "{{ kubernetes_certificates.etcd_client }}"
      - src: "etcd-client-key.pem"
        dest: "{{ kubernetes_certificates.etcd_client_key }}"